<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script type="text/javascript" src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
        <title>aaa</title>
       
    </head>
    <body>
        <div class="container">
            <?php echo $this->getContent(); ?>
        </div>
        <dialog id="a1" open>
          <p>Greetings, one and all!</p>
        </dialog>     
    </body>
</html>
